Clean up examples
Jugsaw/Jugsaw.jl pull request #100
Opened 2023-06-30 04:19 UTC by GiggleLiu

2023-06-30 06:55 UTC, findmyway requested changes

2023-06-30 06:55 UTC, findmyway commented on example/hello_world/Dockerfile
I think `Dockerfile` can also be removed. It is now auto-generated while deploying.

2023-06-30 07:48 UTC, GiggleLiu commented on example/hello_world/Dockerfile
Fixed.

2023-07-04 08:27 UTC, findmyway commented
Closed in favor of #101

2023-07-04 08:27 UTC, closed without merging